"""oauth

Revision ID: 139053b4ea1f
Revises: a1a08f9e0ee8
Create Date: 2024-05-09 15:29:58.678127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139053b4ea1f'
down_revision = 'a1a08f9e0ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_uid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_uid')

    # ### end Alembic commands ###
