"""update tables

Revision ID: 764303738d59
Revises: 39d4b79d6937
Create Date: 2024-04-29 10:40:18.251920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764303738d59'
down_revision = '39d4b79d6937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('east', schema=None) as batch_op:
        batch_op.add_column(sa.Column('western_counterpart', sa.String(), nullable=True))

    with op.batch_alter_table('west', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gloss', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('modality', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('house', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('west', schema=None) as batch_op:
        batch_op.drop_column('house')
        batch_op.drop_column('modality')
        batch_op.drop_column('gloss')

    with op.batch_alter_table('east', schema=None) as batch_op:
        batch_op.drop_column('western_counterpart')

    # ### end Alembic commands ###
