"""update east, west, elements with

Revision ID: 8c8015bfb66b
Revises: c10f9c904bf7
Create Date: 2024-05-06 00:00:09.464848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8015bfb66b'
down_revision = 'c10f9c904bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('east', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_12', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start1', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end1', sa.Date(), nullable=True))

    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    with op.batch_alter_table('west', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('west', schema=None) as batch_op:
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('east', schema=None) as batch_op:
        batch_op.drop_column('end1')
        batch_op.drop_column('start1')
        batch_op.drop_column('end')
        batch_op.drop_column('start')
        batch_op.drop_column('name_12')

    # ### end Alembic commands ###
