"""clean up models and schemas

Revision ID: c10f9c904bf7
Revises: b3a3abc0a596
Create Date: 2024-05-03 20:52:03.917938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10f9c904bf7'
down_revision = 'b3a3abc0a596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('west', schema=None) as batch_op:
        batch_op.alter_column('house',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('west', schema=None) as batch_op:
        batch_op.alter_column('house',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
