"""rm unused columns

Revision ID: ccdcd1bc7f13
Revises: 139053b4ea1f
Create Date: 2024-05-14 14:53:18.478856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdcd1bc7f13'
down_revision = '139053b4ea1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_zodiacs', schema=None) as batch_op:
        batch_op.drop_column('east_west')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_uid')

    with op.batch_alter_table('west', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('west', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_uid', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('user_zodiacs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('east_west', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
